# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneer', '0002_auto_20170419_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
