# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneer', '0003_auto_20170419_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='society',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='wing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
