# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneer', '0004_auto_20170419_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='flat_no',
            field=models.IntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='phase',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
