# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneer', '0005_auto_20170419_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='society',
            table='society',
        ),
    ]
