# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneer', '0007_auto_20170419_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='society',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='society',
            name='flat_no',
            field=models.IntegerField(max_length=500),
        ),
        migrations.AlterField(
            model_name='society',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='society',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='society',
            name='phase',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='society',
            name='society',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='society',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='society',
            name='wing',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='society',
            table=None,
        ),
    ]
