# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneer', '0009_auto_20170419_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societymember',
            name='flat_no',
            field=models.IntegerField(max_length=100),
        ),
    ]
