# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneer', '0010_auto_20170419_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societymember',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
