# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneer', '0011_auto_20170419_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societymember',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='flat_no',
            field=models.IntegerField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='phase',
            field=models.IntegerField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='society',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='wing',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
