# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneer', '0012_auto_20170419_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='societymember',
            options={'verbose_name_plural': 'Society Members'},
        ),
        migrations.AlterField(
            model_name='societymember',
            name='email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='flat_no',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='phase',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='phone_number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='society',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='wing',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='societymember',
            table='societymember',
        ),
    ]
