# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-21 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pioneer', '0015_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocietyMember',
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Member'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='society',
        ),
        migrations.RemoveField(
            model_name='member',
            name='surname',
        ),
        migrations.AddField(
            model_name='member',
            name='society_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=70),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='wing',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='member',
            table='Member',
        ),
    ]
