# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_Articles',
            fields=[
                ('ArticleID', models.AutoField(primary_key=True, serialize=False)),
                ('Heading', models.CharField(max_length=200)),
                ('Comments', models.CharField(max_length=20000)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-active')], max_length=20)),
                ('CreateDate', models.DateField()),
            ],
            options={
                'db_table': 'T_Articles',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='T_Exam',
            fields=[
                ('ExamID', models.AutoField(primary_key=True, serialize=False)),
                ('ExamName', models.CharField(max_length=200)),
                ('CreateDate', models.DateField()),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-active')], max_length=20)),
                ('TimePeriod', models.IntegerField()),
            ],
            options={
                'db_table': 't_exam',
                'verbose_name_plural': 'Exam Papers',
            },
        ),
        migrations.CreateModel(
            name='T_Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-active')], max_length=20)),
                ('CreateDate', models.DateField()),
            ],
            options={
                'db_table': 't_notifications',
                'verbose_name_plural': 'Notification For Students',
            },
        ),
        migrations.CreateModel(
            name='T_QuestionsSet',
            fields=[
                ('QueID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=200)),
                ('A', models.CharField(max_length=200)),
                ('B', models.CharField(max_length=200)),
                ('C', models.CharField(max_length=200)),
                ('D', models.CharField(max_length=200)),
                ('Tip', models.CharField(max_length=200)),
                ('Answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('CreateDate', models.DateField()),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-active')], max_length=20)),
                ('marks', models.CharField(max_length=100)),
                ('ExamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yavatmal.T_Exam')),
            ],
            options={
                'db_table': 't_questionsset',
                'verbose_name_plural': 'Question Bank',
            },
        ),
        migrations.CreateModel(
            name='T_ResultDetail',
            fields=[
                ('ResultDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=200)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-active')], max_length=20)),
                ('Attempted', models.CharField(max_length=200)),
                ('TotalQue', models.CharField(max_length=200)),
                ('MarksObtain', models.CharField(max_length=200)),
                ('TotalMarks', models.CharField(max_length=200)),
                ('FinalResults', models.CharField(max_length=200)),
                ('Percentage', models.CharField(max_length=200)),
                ('CreateDate', models.DateField()),
                ('Subject', models.CharField(max_length=200)),
                ('ExamID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_exam_T_ResultDetail', to='yavatmal.T_Exam')),
            ],
            options={
                'db_table': 'T_ResultDetail',
                'verbose_name_plural': 'Result',
            },
        ),
        migrations.CreateModel(
            name='T_Status',
            fields=[
                ('StatusID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('CreateDate', models.DateField()),
            ],
            options={
                'db_table': 't_status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='T_Subject',
            fields=[
                ('SubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=200)),
                ('CreateDate', models.DateField()),
                ('StatusID', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-active')], max_length=20)),
            ],
            options={
                'db_table': 't_subject',
                'verbose_name_plural': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='T_UserResult',
            fields=[
                ('ResultID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=200)),
                ('CheckAnswer', models.CharField(max_length=20)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-active')], max_length=20)),
                ('CreateDate', models.DateField()),
                ('Question', models.CharField(max_length=200)),
                ('A', models.CharField(max_length=200)),
                ('B', models.CharField(max_length=200)),
                ('C', models.CharField(max_length=200)),
                ('D', models.CharField(max_length=200)),
                ('CorrAnswer', models.CharField(max_length=200)),
                ('ExamID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_exam_t_userresult', to='yavatmal.T_Exam')),
                ('QueID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_questionsset_t_userresult', to='yavatmal.T_QuestionsSet')),
                ('SubjectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_subject_t_userresult', to='yavatmal.T_Subject')),
            ],
            options={
                'db_table': 't_userresult',
                'verbose_name_plural': 'Students Exam Detail',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=200)),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('MobNo', models.IntegerField(max_length=10)),
                ('EmailID', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('DateOfBirth', models.DateField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='t_questionsset',
            name='SubjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yavatmal.T_Subject'),
        ),
        migrations.AddField(
            model_name='t_exam',
            name='SubjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yavatmal.T_Subject'),
        ),
    ]
