# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yavatmal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('MemberID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('society', models.CharField(blank=True, max_length=200)),
                ('phase', models.IntegerField()),
                ('wing', models.CharField(blank=True, max_length=50)),
                ('flat_no', models.IntegerField()),
            ],
            options={
                'db_table': 'Member',
                'verbose_name_plural': 'Member',
            },
        ),
    ]
