# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-15 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yavatmal', '0003_auto_20170421_0735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
