# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-12-15 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yavatmal', '0004_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='MobNo',
            field=models.IntegerField(),
        ),
    ]
